name: tekartik_mdc_js
description: An absolute bare-bones web app.
version: 0.1.0
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  tekartik_browser_utils:
      git: git://github.com/tekartik/tekartik_browser_utils.dart
dev_dependencies:
  tekartik_mdc_asset:
    git: git://github.com/tekartik/mdc_asset.dart
  browser: ">=0.10.0"
  dart_to_js_script_rewriter: ">=1.0.1"
  test: any
  dev_test: any
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart
  tekartik_material_asset:
    git: git://github.com/tekartik/material_asset.dart
  tekartik_app_utils:
    git: git://github.com/tekartik/tekartik_app_utils.dart

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc

dependency_overrides:
#  tekartik_mdc_asset:
#    path: ../mdc_asset.dart

transformers:
- dart_to_js_script_rewriter
