name: tekartik_mdc_js
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  tekartik_browser_utils:
      git: git://github.com/tekartik/tekartik_browser_utils.dart
  mdc: any
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: any
  dev_test: any
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart

transformers:
- dart_to_js_script_rewriter
