name: tekartik_mdc_js
description: An absolute bare-bones web app.
version: 0.2.0
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: dart1
  dart_to_js_script_rewriter: ">=1.0.1"
dev_dependencies:
  tekartik_mdc_asset:
    git:
      url: git://github.com/tekartik/mdc_asset.dart
      ref: dart1
  browser: ">=0.10.0"
  test: any
  dev_test: any
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart1
  tekartik_material_asset:
    git:
      url: git://github.com/tekartik/material_asset.dart
      ref: dart1
  tekartik_app_utils:
    git:
      url: git://github.com/tekartik/app_utils.dart
      ref: dart1

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc

dependency_overrides:
#  tekartik_mdc_asset:
#    path: ../mdc_asset.dart

transformers:
# - dart_to_js_script_rewriter
